name: cm
favicon: null
layout_spectrum: 0.41112
typography_spectrum: 0.34762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3e8a6'
    - '#3e3f40'
    - '#78797a'
    - '#0057d1'
    - '#5086f6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
